apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dnnml3yru-nodejs 
  janus-idp.io/tekton: dnnml3yru-nodejs
  backstage.io/kubernetes-id: dnnml3yru-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dnnml3yru-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml