apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dnnml3yru-nodejs-gitops
  description: This is GitOps manifest for dnnml3yru-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=dnnml3yru-nodejs
    backstage.io/kubernetes-id: dnnml3yru-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: dnnml3yru-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:dnnml3yru-nodejs
